update for cortex-m sys_reset (#96)
* update rust

* update cortex-m fork

* travis: improve rust-toolchain conflict message

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,5 +1,5 @@
 language: rust
-rust: nightly-2019-02-27
+rust: nightly-2019-03-22
 os:
   - linux
   - osx
@@ -30,7 +30,7 @@ before_install:
     rust_toolchain="$(cat rust-toolchain)"
     travis_yml="$(grep '^rust: ' .travis.yml | head -n 1 | sed -E 's/^rust: //')"
     if [[ $travis_yml != $rust_toolchain ]]; then
-      echo "error: the nightly version in $1 is different than the one in rust-toolchain!" 1>&2
+      echo "error: the rust version in travis is different from the one in rust-toolchain!" 1>&2
       exit 1
     fi
 
