travis: ensure consistent toolchain between local and CI

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,5 +1,5 @@
 language: rust
-rust: nightly-2018-12-06
+rust: nightly-2019-02-22
 os:
   - linux
   - osx
@@ -25,6 +25,13 @@ before_install:
     if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^docs)/'; then
       echo "Only docs were updated, stopping build process."
       exit
+    fi
+- |
+    rust_toolchain="$(cat rust-toolchain)"
+    travis_yml="$(grep '^rust: ' .travis.yml | head -n 1 | sed -E 's/^rust: //')"
+    if [[ $travis_yml != $rust_toolchain ]]; then
+      echo "error: the nightly version in $1 is different than the one in rust-toolchain!" 1>&2
+      exit 1
     fi
 
 install:
